---
# USER
admin_user: "can"
admin_groups:
  - "sudo"

# SSH
ssh_port: 53971
ssh_allow_root_login: false

# STORAGE
# Stable by-id device path from Terraform output
k3s_data_device: "/dev/disk/by-id/scsi-0DO_Volume_k3s-main-data"
# Where persistent data will live
k3s_data_mountpoint: "/srv/k3s-data"
# Filesystem settings
k3s_data_fs_type: "ext4"
k3s_data_label: "K3SDATA"

# K3S
k3s_version: "v1.29.3+k3s1"
k3s_install_dir: "/usr/local/bin"
k3s_data_dir: "/srv/k3s-data/k3s"